###
### Elastic Stack
###

version: "3.3"

networks:
  default:

services:
  elastic_stack:
    image: tianon/true
    depends_on:
      - es
      - kb
      - ls

  es:
    image: ${ELASTICSEARCH_IMAGE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - XPACK_EDITION=basic
      - discovery.type=single-node
    ports:
      - 9200:9200/tcp
    networks:
      default:
        aliases:
          - es.local
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

  kb:
    image: ${KIBANA_IMAGE}
    depends_on:
      - es
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - ELASTICSEARCH_URL=http://es.local:9200
    ports:
      - 5601:5601/tcp
    networks:
      default:
        aliases:
          - kb.local
    volumes:
      - kb_data:/usr/share/kibana/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

  ls:
    image: ${LOGSTASH_IMAGE}
    command:
      --pipeline.workers 2
      --path.config pipeline/*.conf
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - LS_HEAP_SIZE=512m
      - ELASTICSEARCH_URL=http://es.local:9200
      - XPACK_MONITORING_ENABLED=true
    networks:
      default:
        aliases:
          - ls.local
    volumes:
      - ls_data:/usr/share/logstash/data
      - ./logstash:/usr/share/logstash/pipeline
      - /var/run/docker.sock:/var/run/docker.sock:ro

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD}
    depends_on:
      - elastic_stack
    env_file:
      - ${TEST_ENV_FILE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - ELASTICSEARCH_CONTAINER=${COMPOSE_PROJECT_NAME}_es_1
      - KIBANA_CONTAINER=${COMPOSE_PROJECT_NAME}_kb_1
      - LOGSTASH_CONTAINER=${COMPOSE_PROJECT_NAME}_ls_1
      - ELASTICSEARCH_URL=http://es.local:9200
      - KIBANA_URL=http://kb.local:5601
      - LOGSTASH_URL=tcp://ls.local:5514
      - WAIT_FOR_TCP=es.local:9200 kb.local:5601 ls.local:5514
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Use project dir as host volume for debugging tests if Docker host is local
      - ${TEST_PROJECT_DIR:-test_project_dir}:${PROJECT_DIR}
    working_dir: ${TEST_DIR}

  wait:
    image: ${TEST_IMAGE}
    depends_on:
      - elastic_stack
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - WAIT_FOR_TCP=es.local:9200 kb.local:5601
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  es_data:
  kb_data:
  ls_data:
  test_project_dir:
