version: 2
jobs:
  build:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc
    steps:
      - checkout
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Pull Docker images
          command: |
            make docker-pull-dependencies
            make docker-pull-testimage
      - run:
          name: sicz/elastic-stack:2.4.6
          working_directory: 2.4.6
          command: |
            make ci
      - run:
          name: sicz/elastic-stack:6.1.2
          working_directory: 6.1.2
          command: |
            make ci
